PYTHON_INTERPRETER=python3
PYPATH=../../
.PHONY: all

all:
	@-echo "Nothing to do...";

base_object:
	@-PYTHONPATH=$(PYPATH) $(PYTHON_INTERPRETER) base_object.py;

base_time:
	@-PYTHONPATH=$(PYPATH) $(PYTHON_INTERPRETER) base_time.py;