BASEDIR=$(PWD)/tests/basics/
PYTHON_INTERPRETER=python3
PYTHONPATH=../../

run_all: camera game_object
	
camera:
	@-$(PYTHON_INTERPRETER) $(BASEDIR)/camera.py;

game_object:
	@-$(PYTHON_INTERPRETER) $(BASEDIR)/game_object.py;