#!/bin/bash
#
#   Configurations for the game engine

#PYMIR_REPO_DIRECTORY=`dirname $PYMIR_SCRIPTS_DIRECTORY`;
export PYMIR_REPO_DIRECTORY=`realpath $(dirname $PYMIR_SCRIPTS_DIRECTORY)`;
export PYMIR_ENVIRONMENT_DIRECTORY=$PYMIR_REPO_DIRECTORY;
export PYMIR_IMAGE_DIRECTORY="$PYMIR_REPO_DIRECTORY";

verbose() {
    echo $PYMIR_REPO_DIRECTORY;
    echo $PYMIR_ENVIRONMENT_DIRECTORY;
    echo $PYMIR_IMAGE_DIRECTORY;
}

python -m venv $PYMIR_ENVIRONMENT_DIRECTORY;